Repository algolia/algoliasearch-client-java-2, pull requests merged in 2019-04, with the labels that each got.

#549 Added: Configuration Builder
  src/main/java/com/algolia/search/AnalyticsClient.java
  src/main/java/com/algolia/search/AnalyticsConfig.java
  src/main/java/com/algolia/search/ConfigBase.java
  src/main/java/com/algolia/search/InsightsClient.java
  src/main/java/com/algolia/search/InsightsConfig.java
  src/main/java/com/algolia/search/RetryStrategy.java
  src/main/java/com/algolia/search/SearchClient.java
  src/main/java/com/algolia/search/SearchConfig.java
  src/test/java/com/algolia/search/RetryStrategyTest.java
  src/test/java/com/algolia/search/integration/client/TimeoutTest.java
Labels: Chore, Do not merge

#550 test: Limit variables' scope
  src/test/java/com/algolia/search/integration/analytics/AnalyticsTest.java
  src/test/java/com/algolia/search/integration/client/ApiKeysTest.java
  src/test/java/com/algolia/search/integration/client/CopyIndexTest.java
  src/test/java/com/algolia/search/integration/client/MultiClusterManagementTest.java
  src/test/java/com/algolia/search/integration/client/MultipleOperationsTest.java
  src/test/java/com/algolia/search/integration/client/SecuredAPIKeyTest.java
  src/test/java/com/algolia/search/integration/index/BatchingTest.java
  src/test/java/com/algolia/search/integration/index/IndexingTest.java
  src/test/java/com/algolia/search/integration/index/QueryRulesTest.java
  src/test/java/com/algolia/search/integration/index/ReplacingTest.java
  src/test/java/com/algolia/search/integration/index/SearchTest.java
  src/test/java/com/algolia/search/integration/index/SettingsTest.java
  src/test/java/com/algolia/search/integration/index/SynonymsTest.java
  src/test/java/com/algolia/search/integration/insights/InsightsTest.java
Labels: Do not merge

#551 tests: Split "core" and "apache"
  src/main/java/com/algolia/search/ApacheHttpRequester.java
  src/test/java/com/algolia/search/apache/account/AccountCopyTest.java
  src/test/java/com/algolia/search/apache/analytics/AnalyticsTest.java
  src/test/java/com/algolia/search/apache/client/ApiKeysTest.java
  src/test/java/com/algolia/search/apache/client/CopyIndexTest.java
  src/test/java/com/algolia/search/apache/client/LogsTest.java
  src/test/java/com/algolia/search/apache/client/MultiClusterManagementTest.java
  src/test/java/com/algolia/search/apache/client/MultipleOperationsTest.java
  src/test/java/com/algolia/search/apache/client/SecuredAPIKeyTest.java
  src/test/java/com/algolia/search/apache/client/TimeoutTest.java
  src/test/java/com/algolia/search/apache/index/BatchingTest.java
  src/test/java/com/algolia/search/apache/index/IndexingTest.java
  src/test/java/com/algolia/search/apache/index/QueryRulesTest.java
  src/test/java/com/algolia/search/apache/index/ReplacingTest.java
  src/test/java/com/algolia/search/apache/index/SearchTest.java
  src/test/java/com/algolia/search/apache/index/SettingsTest.java
  src/test/java/com/algolia/search/apache/index/SynonymsTest.java
  src/test/java/com/algolia/search/apache/insights/InsightsTest.java
  src/test/java/com/algolia/search/integration/account/AccountCopyTest.java
  src/test/java/com/algolia/search/integration/analytics/AnalyticsTest.java
  src/test/java/com/algolia/search/integration/client/ApiKeysTest.java
  src/test/java/com/algolia/search/integration/client/CopyIndexTest.java
  src/test/java/com/algolia/search/integration/client/LogsTest.java
  src/test/java/com/algolia/search/integration/client/MultiClusterManagementTest.java
  src/test/java/com/algolia/search/integration/client/MultipleOperationsTest.java
  src/test/java/com/algolia/search/integration/client/SecuredAPIKeyTest.java
  src/test/java/com/algolia/search/integration/client/TimeoutTest.java
  src/test/java/com/algolia/search/integration/index/BatchingTest.java
  src/test/java/com/algolia/search/integration/index/IndexingTest.java
  src/test/java/com/algolia/search/integration/index/QueryRulesTest.java
  src/test/java/com/algolia/search/integration/index/ReplacingTest.java
  src/test/java/com/algolia/search/integration/index/SearchTest.java
  src/test/java/com/algolia/search/integration/index/SettingsTest.java
  src/test/java/com/algolia/search/integration/index/SynonymsTest.java
  src/test/java/com/algolia/search/integration/insights/InsightsTest.java
Labels: Discussion, Do not merge

#552 test: Detach "core" from "apache"
  src/test/java/com/algolia/search/apache/IntegrationTestExtension.java
  src/test/java/com/algolia/search/apache/account/AccountCopyTest.java
  src/test/java/com/algolia/search/apache/analytics/AnalyticsTest.java
  src/test/java/com/algolia/search/apache/client/ApiKeysTest.java
  src/test/java/com/algolia/search/apache/client/CopyIndexTest.java
  src/test/java/com/algolia/search/apache/client/LogsTest.java
  src/test/java/com/algolia/search/apache/client/MultiClusterManagementTest.java
  src/test/java/com/algolia/search/apache/client/MultipleOperationsTest.java
  src/test/java/com/algolia/search/apache/client/SecuredAPIKeyTest.java
  src/test/java/com/algolia/search/apache/client/TimeoutTest.java
  src/test/java/com/algolia/search/apache/index/BatchingTest.java
  src/test/java/com/algolia/search/apache/index/IndexingTest.java
  src/test/java/com/algolia/search/apache/index/QueryRulesTest.java
  src/test/java/com/algolia/search/apache/index/ReplacingTest.java
  src/test/java/com/algolia/search/apache/index/SearchTest.java
  src/test/java/com/algolia/search/apache/index/SettingsTest.java
  src/test/java/com/algolia/search/apache/index/SynonymsTest.java
  src/test/java/com/algolia/search/apache/insights/InsightsTest.java
  src/test/java/com/algolia/search/integration/TestHelpers.java
  src/test/java/com/algolia/search/integration/account/AccountCopyTest.java
  src/test/java/com/algolia/search/integration/analytics/AnalyticsTest.java
  src/test/java/com/algolia/search/integration/client/CopyIndexTest.java
  src/test/java/com/algolia/search/integration/client/MultiClusterManagementTest.java
  src/test/java/com/algolia/search/integration/client/MultipleOperationsTest.java
  src/test/java/com/algolia/search/integration/client/SecuredAPIKeyTest.java
  src/test/java/com/algolia/search/integration/index/IndexingTest.java
  src/test/java/com/algolia/search/integration/index/QueryRulesTest.java
  src/test/java/com/algolia/search/integration/index/ReplacingTest.java
  src/test/java/com/algolia/search/integration/index/SearchTest.java
  src/test/java/com/algolia/search/integration/index/SettingsTest.java
  src/test/java/com/algolia/search/integration/index/SynonymsTest.java
  src/test/java/com/algolia/search/integration/insights/InsightsTest.java
Labels: Do not merge

#558 Added: sl4j logger in HttpTransport
  algoliasearch-core/src/main/java/com/algolia/search/HttpTransport.java
Labels: Do not merge, Enhancement

#559 packaging: Generate uber jars for -core and -apache
  algoliasearch-apache-uber/pom.xml
  algoliasearch-core-uber/pom.xml
  pom.xml
Labels: Do not merge, Enhancement
